"""Typed operators for the text, language, logic and code-generation modules of the tool library."""
from __future__ import annotations

from typing import Any

from scienceclaw.program.specs._common import p

# id, tool, description, inputs, outputs, body of run(), pre, post, applicability tags
SPECS: list[dict[str, Any]] = [
    dict(id="caption_chrf_score", tool="captions.mean_chrf",
         description="Sentence-level chrF++ (character 1-6-grams and word 1-2-grams, beta 2, the sacrebleu CHRF(word_order=2) definition) of candidate captions against a pool of reference captions of one language; the score of a candidate is its mean over the references.",
         inputs={"hypotheses": p("list", "candidate caption strings"),
                 "references": p("list", "reference caption strings of the same language")},
         outputs={"scores": p("array", "mean chrF++ of every candidate against all references, 0 to 100", shape=("n_hypotheses",), unit="chrF++", dtype="float")},
         code="import numpy as np\nfrom scilib import captions\nrefs = [str(r) for r in inputs['references']]\nreturn {'scores': np.array([captions.mean_chrf(str(h), refs) for h in inputs['hypotheses']], dtype=float)}",
         pre=[{"port": "hypotheses", "check": "nonempty"}, {"port": "references", "check": "nonempty"}],
         post=[{"port": "scores", "check": "finite"}, {"port": "scores", "check": "range", "value": [0, 100]}],
         tags=["captions", "chrf", "machine translation metric", "text", "evaluation"]),
    dict(id="caption_consensus_string", tool="captions.consensus_caption",
         description="One caption string for a language that maximises the mean chrF++ against its pool of captions: greedy word-by-word search over the most frequent words (not a grammatical sentence), falling back to the medoid caption when that scores higher.",
         inputs={"captions": p("list", "caption strings of ONE language"),
                 "max_words": p("number", "maximum number of words of the string", unit="1")},
         outputs={"caption": p("text", "caption string built for the pool")},
         code="from scilib import captions\nreturn {'caption': captions.consensus_caption(inputs['captions'], max_words=int(inputs['max_words']))}",
         pre=[{"port": "captions", "check": "nonempty"}], post=[{"port": "caption", "check": "nonempty"}],
         tags=["captions", "chrf", "consensus", "minimum Bayes risk", "text generation"]),
    dict(id="caption_mbr_clauses", tool="captions.mbr_caption",
         description="Caption for a language assembled from whole clauses of its caption pool, greedily chosen to maximise the mean chrF++ against the pool (minimum-Bayes-risk selection of clauses; every clause occurs in a given caption).",
         inputs={"captions": p("list", "caption strings of ONE language"),
                 "max_words": p("number", "maximum number of words of the result", unit="1")},
         outputs={"caption": p("text", "sequence of clauses taken from the pool")},
         code="from scilib import captions\nreturn {'caption': captions.mbr_caption(inputs['captions'], max_words=int(inputs['max_words']))}",
         pre=[{"port": "captions", "check": "nonempty"}], post=[{"port": "caption", "check": "nonempty"}],
         tags=["captions", "chrf", "minimum Bayes risk", "text generation"]),
    dict(id="caption_medoid", tool="captions.medoid",
         description="The medoid of a pool of captions of one language: the distinct caption with the highest mean chrF++ against the other captions.",
         inputs={"captions": p("list", "caption strings of ONE language")},
         outputs={"caption": p("text", "the most central caption of the pool")},
         code="from scilib import captions\nreturn {'caption': captions.medoid(inputs['captions'])}",
         pre=[{"port": "captions", "check": "nonempty"}], post=[{"port": "caption", "check": "nonempty"}],
         tags=["captions", "chrf", "medoid", "text"]),
    dict(id="caption_holdout_chrf_estimate", tool="captions.loo_score",
         description="Leave-out estimate of the mean chrF++ that a caption-building strategy (medoid, consensus or mbr) reaches on captions it did not see, from repeated random train/test splits of the pool of one language.",
         inputs={"captions": p("list", "caption strings of ONE language"),
                 "strategy": p("text", "'medoid', 'consensus' or 'mbr'"),
                 "n_repeats": p("number", "random splits per fold size", unit="1")},
         outputs={"estimate": p("dict", "{'mean', 'sem', 'n_folds', 'n_test', 'per_language'}: chrF++ on held-out captions")},
         code="from scilib import captions\nreturn {'estimate': captions.loo_score(inputs['captions'], str(inputs['strategy']), n_repeats=int(inputs['n_repeats']), max_folds=12)}",
         pre=[{"port": "captions", "check": "nonempty"}], post=[],
         tags=["captions", "chrf", "validation", "cross-validation", "text"]),
    dict(id="code_generation_prompts", tool="codegen.build_prompts",
         description="Prompts that ask a language model for one fenced python block with the complete function of each programming problem (task text or stub, public tests, time limit); styles direct, plan and examples (HumanEval / MBPP style function completion).",
         inputs={"problems": p("list", "problem dicts with keys prompt, entry_point, visible_tests (assert lines) and kind ('python_function_stub' or other)"),
                 "style": p("text", "'direct', 'plan' or 'examples'")},
         outputs={"prompts": p("list", "one prompt string per problem")},
         code="from scilib import codegen\nreturn {'prompts': codegen.build_prompts(inputs['problems'], style=str(inputs['style']))}",
         pre=[{"port": "problems", "check": "nonempty"}], post=[{"port": "prompts", "check": "nonempty"}],
         tags=["code generation", "python", "prompt", "humaneval", "language model"]),
    dict(id="code_reply_sanitize", tool="codegen.sanitize",
         description="Turns language-model replies (fenced code, bare bodies, truncated fences, prose) into runnable python sources: keeps the entry-point function with the imports and helpers it uses, drops demo code, prepends a standard prelude, and substitutes a failing placeholder for unusable replies.",
         inputs={"texts": p("list", "reply strings of the model, None for a failed request, one per problem"),
                 "problems": p("list", "the problem dicts the replies belong to (prompt, entry_point, kind)")},
         outputs={"programs": p("list", "one python source per problem; for stub problems it is appended to the problem's prompt")},
         code="from scilib import codegen\nreturn {'programs': codegen.sanitize(inputs['texts'], inputs['problems'])}",
         pre=[{"port": "texts", "check": "nonempty"}, {"port": "problems", "check": "nonempty"}],
         post=[{"port": "programs", "check": "nonempty"}],
         tags=["code generation", "python", "post-processing", "language model"]),
    dict(id="code_repair_prompts", tool="codegen.repair_prompts",
         description="Prompts for a language model to repair the programs that fail their public tests (failing assertions and the error text are quoted); programs that are only the placeholder get a fresh generation prompt.",
         inputs={"problems": p("list", "problem dicts (prompt, entry_point, kind)"),
                 "programs": p("list", "current python source per problem"),
                 "results": p("list", "per-problem test results: dicts with passed, failing_tests, error, n_tests, n_passed")},
         outputs={"prompts": p("list", "one repair prompt per failing problem"),
                  "index": p("list", "positions of the failing problems, aligned with the prompts")},
         code="from scilib import codegen\nr = codegen.repair_prompts(inputs['problems'], inputs['programs'], inputs['results'])\nreturn {'prompts': r['prompts'], 'index': r['index']}",
         pre=[{"port": "problems", "check": "nonempty"}], post=[],
         tags=["code generation", "python", "debugging", "self-repair", "language model"]),
    dict(id="code_select_best_candidate", tool="codegen.select_best",
         description="Per problem, the candidate program that passes the most public tests (a program with passed=true and the largest n_passed; earlier candidate set wins ties).",
         inputs={"candidate_sets": p("list", "list of program lists, each as long as the problem list"),
                 "results": p("list", "one test-result list (or dict with key results) per candidate set")},
         outputs={"programs": p("list", "chosen python source per problem")},
         code="from scilib import codegen\nreturn {'programs': codegen.select_best(inputs['candidate_sets'], inputs['results'])}",
         pre=[{"port": "candidate_sets", "check": "nonempty"}], post=[{"port": "programs", "check": "nonempty"}],
         tags=["code generation", "python", "selection", "candidate ranking"]),
    dict(id="ocr_character_error_rate", tool="ocrfix.score",
         description="Character match error rate (cMER = (S+D+I)/(H+S+D+I) after lower-casing, ligature mapping and punctuation removal) of OCR post-correction hypotheses against gold transcriptions, per unit and as the weighted micro average over test sets.",
         inputs={"golds": p("list", "gold transcription strings"),
                 "hypotheses": p("list", "corrected text strings, one per gold"),
                 "test_sets": p("list", "test-set name per unit (dta19-l0/l1/l2 weigh 1/3, all others 1)")},
         outputs={"weighted_cmer_micro": p("number", "weighted micro-averaged cMER, lower is better", unit="1"),
                  "per_unit_cmer": p("array", "cMER of each unit", shape=("n_units",), unit="1", dtype="float")},
         code="import numpy as np\nfrom scilib import ocrfix\nr = ocrfix.score(inputs['test_sets'], inputs['golds'], inputs['hypotheses'])\nper = np.array([ocrfix.cmer(g, h) for g, h in zip(inputs['golds'], inputs['hypotheses'])], dtype=float)\nreturn {'weighted_cmer_micro': float(r['weighted_cmer_micro']), 'per_unit_cmer': per}",
         pre=[{"port": "golds", "check": "nonempty"}], post=[{"port": "weighted_cmer_micro", "check": "finite"}, {"port": "per_unit_cmer", "check": "range", "value": [0, 1]}],
         tags=["ocr", "post-correction", "historical text", "error rate", "evaluation"]),
    dict(id="ocr_noise_profile", tool="ocrfix.noise_profile",
         description="Per test set statistics of aligned OCR / gold training pairs: number of units, OCR cMER, unit cMER percentiles, gold-to-OCR length ratio, end-of-line hyphens and the gain from joining line-break hyphens.",
         inputs={"train": p("list", "dicts with ocr_text, gt_text and test_set")},
         outputs={"profile": p("dict", "{test_set: {n, ocr_cmer, unit_cmer_p50, unit_cmer_p90, unit_cmer_max, length_ratio_p05, length_ratio_p95, line_hyphens, hyphen_join_gain}}")},
         code="from scilib import ocrfix\nreturn {'profile': ocrfix.noise_profile(inputs['train'])}",
         pre=[{"port": "train", "check": "nonempty"}], post=[{"port": "profile", "check": "nonempty"}],
         tags=["ocr", "post-correction", "historical text", "noise statistics"]),
    dict(id="ocr_correction_plan", tool="ocrfix.plan",
         description="Cuts OCR units into balanced chunks and builds one language-model correction prompt per chunk (error-kind instructions plus aligned OCR / gold excerpts of the same test set); units of near-perfect test sets are skipped.",
         inputs={"units": p("list", "dicts with ocr_text, language and test_set"),
                 "train": p("list", "labelled pairs with ocr_text, gt_text and test_set (may be empty)"),
                 "max_chars": p("number", "target characters per chunk", unit="1")},
         outputs={"plan": p("dict", "plan with items, units and settings, to pass to ocr_guarded_merge"),
                  "prompts": p("list", "prompt string of every chunk, in item order")},
         code="from scilib import ocrfix\nplan = ocrfix.plan(inputs['units'], inputs['train'], max_chars=int(inputs['max_chars']))\nreturn {'plan': plan, 'prompts': [it['prompt'] for it in plan['items']]}",
         pre=[{"port": "units", "check": "nonempty"}], post=[{"port": "plan", "check": "nonempty"}],
         tags=["ocr", "post-correction", "historical text", "language model", "prompt"]),
    dict(id="ocr_guarded_merge", tool="ocrfix.merge",
         description="Reassembles corrected chunks into unit texts, accepting a model reply only when its length ratio, edit rate and word-level hunks stay within bounds; rejected or empty replies keep the OCR text.",
         inputs={"plan": p("dict", "output of ocr_correction_plan"),
                 "replies": p("list", "model reply per chunk, in the order of the plan's prompts (None for a failed request)")},
         outputs={"texts": p("list", "corrected text of every unit, in the order of the plan's units"),
                  "report": p("dict", "counts of chunks sent, rejected (by reason), hunks taken and kept")},
         code="from scilib import ocrfix\nr = ocrfix.merge(inputs['plan'], inputs['replies'])\nreturn {'texts': r['y'], 'report': r['report']}",
         pre=[{"port": "plan", "check": "nonempty"}], post=[{"port": "texts", "check": "nonempty"}],
         tags=["ocr", "post-correction", "historical text", "guardrail", "language model"]),
    dict(id="human_value_multilabel_predict", tool="valueeval.fit_predict",
         description="Multi-label human-value detection in arguments (Touche23 ValueEval): TF-IDF logistic regressions per value with grouped out-of-fold Platt calibration, then the 0/1 decision that maximises the expected official F1 over rows scored together; about a minute for 1,000 training arguments on two cores.",
         inputs={"train": p("table", "training arguments with columns conclusion, stance ('in favor of' / 'against') and premise"),
                 "labels": p("array", "0/1 value labels of the training rows", shape=("n_train", "n_values"), dtype="int"),
                 "targets": p("table", "arguments to label, same columns as train")},
         outputs={"predictions": p("array", "0/1 value assignments", shape=("n_targets", "n_values"), dtype="int"),
                  "probabilities": p("array", "calibrated probability of each value", shape=("n_targets", "n_values"), dtype="float")},
         code="import numpy as np\nfrom scilib import valueeval\npred = valueeval.fit_predict(inputs['train'], inputs['labels'], [inputs['targets']], n_folds=3)\nreturn {'predictions': np.asarray(pred[0], dtype=int), 'probabilities': np.asarray(pred.probs[0], dtype=float)}",
         pre=[{"port": "train", "check": "nonempty"}], post=[{"port": "probabilities", "check": "finite"}, {"port": "probabilities", "check": "range", "value": [0, 1]}],
         tags=["argument mining", "human values", "multi-label classification", "text", "semeval", "tf-idf"]),
    dict(id="value_detection_official_f1", tool="valueeval.official_f1_report",
         description="Official ValueEval'23 F1 (harmonic mean of macro precision and macro recall over the values with a gold positive) of 0/1 predictions against 0/1 gold labels.",
         inputs={"y_true": p("array", "0/1 gold labels", shape=("n", "n_values"), dtype="int"),
                 "y_pred": p("array", "0/1 predictions", shape=("n", "n_values"), dtype="int")},
         outputs={"f1": p("number", "official F1", unit="1"),
                  "report": p("dict", "f1, precision, recall, mean_category_f1, n_categories")},
         code="from scilib import valueeval\nr = valueeval.official_f1_report(inputs['y_true'], inputs['y_pred'])\nreturn {'f1': float(r['f1']), 'report': r}",
         pre=[{"port": "y_true", "check": "finite"}], post=[{"port": "f1", "check": "finite"}],
         tags=["argument mining", "human values", "multi-label classification", "evaluation", "f1"]),
    dict(id="smt_satisfiability_batch", tool="logic.solve_all",
         description="Satisfiability (sat / unsat / unknown) of SMT-LIB scripts (QF_NIA, QF_LIA and related logics) with the Z3 solver, a wall-clock limit per query and several queries in parallel.",
         inputs={"queries": p("list", "SMT-LIB script strings"),
                 "timeout_s": p("number", "wall-clock limit per query", unit="s")},
         outputs={"status": p("list", "'sat', 'unsat' or 'unknown' per query"),
                  "seconds": p("array", "solver wall time per query", shape=("n_queries",), unit="s", dtype="float")},
         code="import numpy as np\nfrom scilib import logic\nres = logic.solve_all(inputs['queries'], threads=2, timeout_s=float(inputs['timeout_s']))\nreturn {'status': [r['status'] for r in res], 'seconds': np.array([r['seconds'] for r in res], dtype=float)}",
         pre=[{"port": "queries", "check": "nonempty"}], post=[{"port": "status", "check": "nonempty"}],
         tags=["logic", "SMT", "z3", "satisfiability", "constraint solving", "nonlinear integer arithmetic"]),
    dict(id="smt_escalating_decide", tool="logic.decide",
         description="Decides a batch of SMT-LIB scripts with Z3 under one wall-clock budget by escalating resource limits over rounds; undecided queries get a fallback label (unknown, sat, unsat or the majority of the known training statuses).",
         inputs={"queries": p("list", "SMT-LIB script strings"),
                 "train_status": p("list", "statuses ('sat' / 'unsat') of labelled training queries, used by the 'majority' fallback (may be empty)"),
                 "fallback": p("text", "label of undecided queries: 'unknown', 'sat', 'unsat' or 'majority'"),
                 "budget_s": p("number", "wall-clock budget of the whole batch", unit="s")},
         outputs={"labels": p("list", "final label per query (Z3's answer if decided, else the fallback)"),
                  "decided": p("array", "True where Z3 itself decided the query", shape=("n_queries",), dtype="bool")},
         code="import numpy as np\nfrom scilib import logic\nr = logic.decide(inputs['queries'], train_status=list(inputs['train_status']) or None, fallback=str(inputs['fallback']), budget_s=float(inputs['budget_s']))\nreturn {'labels': r['labels'], 'decided': np.array([s != 'unknown' for s in r['status']], dtype=bool)}",
         pre=[{"port": "queries", "check": "nonempty"}], post=[{"port": "labels", "check": "nonempty"}],
         tags=["logic", "SMT", "z3", "satisfiability", "time budget", "nonlinear integer arithmetic"]),
    dict(id="ud_parser_train_parse", tool="udparse.UDParser",
         description="Trains a Universal Dependencies tagger and graph-based dependency parser (averaged passive-aggressive arc scorer, Eisner or Chu-Liu/Edmonds decoding) on annotated sentences and parses new tokenised sentences; works for any treebank language; about a minute for 400 training sentences.",
         inputs={"train": p("list", "annotated sentences {'words': [{'form', 'upos', 'feats', 'head' (1-based, 0 root), 'deprel'}]}"),
                 "targets": p("list", "sentences to parse, {'words': [{'form': ...}]} or lists of word forms"),
                 "decode": p("text", "'eisner' (projective) or 'cle' (non-projective)")},
         outputs={"parses": p("list", "per sentence {'head': [...], 'deprel': [...]}, a valid single-root tree"),
                  "upos": p("list", "predicted UPOS tags per sentence")},
         code="from scilib import udparse\nm = udparse.UDParser(decode=str(inputs['decode'])).fit(inputs['train'])\nreturn {'parses': m.parse(inputs['targets']), 'upos': m.tag(inputs['targets'])}",
         pre=[{"port": "train", "check": "nonempty"}, {"port": "targets", "check": "nonempty"}], post=[{"port": "parses", "check": "nonempty"}],
         tags=["linguistics", "parsing", "dependency parsing", "universal dependencies", "pos tagging", "treebank"]),
    dict(id="ud_attachment_scores", tool="udparse.las_uas",
         description="Labeled and unlabeled attachment scores (CoNLL 2018 LAS and UAS, punctuation included, universal relation labels) of dependency parses against annotated gold sentences.",
         inputs={"gold": p("list", "annotated sentences with head and deprel"),
                 "parses": p("list", "per sentence {'head': [...], 'deprel': [...]}")},
         outputs={"las": p("number", "labeled attachment score", unit="1"), "uas": p("number", "unlabeled attachment score", unit="1")},
         code="from scilib import udparse\nr = udparse.las_uas(inputs['gold'], inputs['parses'])\nreturn {'las': float(r['las']), 'uas': float(r['uas'])}",
         pre=[{"port": "gold", "check": "nonempty"}], post=[{"port": "las", "check": "range", "value": [0, 1]}, {"port": "uas", "check": "range", "value": [0, 1]}],
         tags=["linguistics", "parsing", "dependency parsing", "universal dependencies", "evaluation"]),
    dict(id="dependency_tree_decode", tool="udparse.eisner",
         description="Maximum-scoring single-root dependency tree from a head-by-dependent arc-score matrix: projective Eisner or non-projective Chu-Liu/Edmonds decoding.",
         inputs={"arc_scores": p("array", "scores[h, d-1] of the arc from head h (row 0 = artificial root) to word d", shape=("n_plus_1", "n"), dtype="float"),
                 "method": p("text", "'eisner' (projective) or 'cle' (any tree)")},
         outputs={"heads": p("array", "1-based head of every word, 0 for the root", shape=("n",), dtype="int")},
         code="import numpy as np\nfrom scilib import udparse\nf = udparse.eisner if str(inputs['method']) == 'eisner' else udparse.chu_liu_edmonds\nreturn {'heads': np.asarray(f(inputs['arc_scores']), dtype=int)}",
         pre=[{"port": "arc_scores", "check": "finite"}], post=[{"port": "heads", "check": "nonempty"}],
         tags=["linguistics", "parsing", "dependency parsing", "maximum spanning tree", "decoding"]),
    dict(id="contract_evidence_identification", tool="contracts.fit_predict",
         description="Evidence identification and entailment / contradiction labelling for contract clauses (ContractNLI): span-level logistic regressions per hypothesis then a LightGBM re-ranker, fitted on annotated training contracts and applied to (contract, hypothesis) pairs; fitting takes minutes for tens of contracts.",
         inputs={"train_documents": p("list", "contracts as {'doc_id', 'span_texts'}"),
                 "train_annotations": p("list", "{'doc_id', 'hypothesis_key', 'label' (Entailment / Contradiction / NotMentioned), 'evidence_spans' (span indices)}"),
                 "hypotheses": p("dict", "hypothesis_key -> {'hypothesis': text, 'short_description': text}"),
                 "items": p("list", "pairs to predict as {'doc_id', 'hypothesis_key'}"),
                 "documents": p("list", "the contracts of the items, as {'doc_id', 'span_texts'}")},
         outputs={"predictions": p("list", "per item {'label': 'Entailment' | 'Contradiction', 'span_scores': one score in [0, 1] per span}")},
         code="from scilib import contracts\nreturn {'predictions': contracts.fit_predict(inputs['train_documents'], inputs['train_annotations'], inputs['hypotheses'], inputs['items'], inputs['documents'])}",
         pre=[{"port": "train_documents", "check": "nonempty"}, {"port": "items", "check": "nonempty"}], post=[{"port": "predictions", "check": "nonempty"}],
         tags=["contracts", "legal", "natural language inference", "evidence retrieval", "span ranking", "lightgbm"]),
    dict(id="contract_evidence_metrics", tool="contracts.evaluate_predictions",
         description="Mean average precision and precision at 80 percent recall of span rankings against gold evidence spans, plus the entailment / contradiction accuracy (ContractNLI evaluation).",
         inputs={"predictions": p("list", "per pair {'label', 'span_scores'}"),
                 "gold": p("list", "per pair a 0/1 vector over the spans marking the gold evidence"),
                 "labels": p("list", "gold label per pair, 'Entailment' or 'Contradiction'")},
         outputs={"metrics": p("dict", "map, p_at_r80, nli_binary_accuracy and the per-pair average precisions (aps)")},
         code="from scilib import contracts\nreturn {'metrics': contracts.evaluate_predictions(inputs['predictions'], inputs['gold'], inputs['labels'])}",
         pre=[{"port": "predictions", "check": "nonempty"}], post=[{"port": "metrics", "check": "nonempty"}],
         tags=["contracts", "legal", "evaluation", "average precision", "span ranking"]),
    dict(id="choice_next_response_predict", tool="psych.fit_predict",
         description="Predicts the next key press of a participant from the transcript of their earlier trials with choice models fitted per participant (choice kernel, Q-learning with softmax and perseveration, win-stay lose-shift, mixtures) or a population gradient-boosting model (Psych-101 / Psych-201 style sessions with <<KEY>> markers).",
         inputs={"items": p("list", "dicts {'study', 'history' (transcript before the response), 'options' (legal keys)}"),
                 "train_sessions": p("list", "complete sessions of other participants {'study', 'text', 'responses': [{'pos', 'response', 'options'}]} (may be empty)"),
                 "method": p("text", "'mode', 'last', 'kernel', 'qlearn', 'wsls', 'personal', 'gbdt' or 'auto'")},
         outputs={"predictions": p("list", "predicted legal key per item"),
                  "probabilities": p("list", "per item {key: probability}")},
         code="from scilib import psych\nkeys, proba = psych.fit_predict(inputs['items'], inputs['train_sessions'], method=str(inputs['method']), return_proba=True)\nreturn {'predictions': keys, 'probabilities': proba}",
         pre=[{"port": "items", "check": "nonempty"}], post=[{"port": "predictions", "check": "nonempty"}],
         tags=["psychology", "cognitive modelling", "human behaviour", "reinforcement learning", "choice prediction", "psych-201"]),
    dict(id="choice_model_cross_validate", tool="psych.cross_validate",
         description="Out-of-fold accuracy of a next-choice predictor on pseudo-items cut from complete participant sessions, folds grouped by participant, against the participant-mode baseline, overall and per study.",
         inputs={"sessions": p("list", "complete sessions {'study', 'text', 'responses': [{'pos', 'response', 'options'}]}"),
                 "method": p("text", "'mode', 'last', 'kernel', 'qlearn', 'wsls', 'personal', 'gbdt' or 'auto'"),
                 "n_splits": p("number", "number of folds", unit="1")},
         outputs={"scores": p("dict", "accuracy, mode_accuracy, n_items and by_study accuracies")},
         code="from scilib import psych\nreturn {'scores': psych.cross_validate(inputs['sessions'], method=str(inputs['method']), n_splits=int(inputs['n_splits']), per_session=2)}",
         pre=[{"port": "sessions", "check": "nonempty"}], post=[{"port": "scores", "check": "nonempty"}],
         tags=["psychology", "cognitive modelling", "human behaviour", "validation", "choice prediction", "psych-201"]),
    dict(id="choice_llm_prompts", tool="psych.build_prompts",
         description="One prompt per participant item for a language model: the experiment instructions, the latest trials of the transcript with the participant's <<KEY>> responses, the legal keys and the question which key is pressed next.",
         inputs={"items": p("list", "dicts {'study', 'history', 'options'}"),
                 "style": p("text", "'transcript' or 'long'")},
         outputs={"prompts": p("list", "prompt string per item")},
         code="from scilib import psych\nreturn {'prompts': psych.build_prompts(inputs['items'], style=str(inputs['style']))}",
         pre=[{"port": "items", "check": "nonempty"}], post=[{"port": "prompts", "check": "nonempty"}],
         tags=["psychology", "human behaviour", "prompt", "language model", "choice prediction"]),
    dict(id="choice_llm_answers_parse", tool="psych.parse_answers",
         description="Reads the key named by each language-model reply of the next-choice prompts (quotes, brackets and <<>> stripped); None where no single legal key can be read.",
         inputs={"texts": p("list", "reply strings (None for a failed request), one per item"),
                 "items": p("list", "dicts with the legal 'options' of every item")},
         outputs={"keys": p("list", "key per item or None")},
         code="from scilib import psych\nreturn {'keys': psych.parse_answers(inputs['texts'], inputs['items'])}",
         pre=[{"port": "items", "check": "nonempty"}], post=[{"port": "keys", "check": "nonempty"}],
         tags=["psychology", "human behaviour", "language model", "answer parsing", "choice prediction"]),
]
